---
- name: install tomcat server
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: install updates using yum
    yum:
      name: "*"
      state: latest

  - name: install java 1.8.0 open JDK
    shell: "yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel"
    #shell: "yum -y install java-1.7.0-openjdk" java-1.7.0-openjdk-devel"
    #shell: "yum -y install java-1.9.0-openjdk" java-1.9.0-openjdk-devel"


  - name: add group "tomcat"
    group: name=tomcat

  - name: add user "tomcat"
    user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no

  - name: Download Tomcat 10
    get_url: url=http://archive.apache.org/dist/tomcat/tomcat-10/v10.0.7/bin/apache-tomcat-10.0.7.tar.gz dest=/usr/share/apache-tomcat-10.0.7.tar.gz

 # - name: Download Tomcat 8
 #   get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.tar.gz


  - name: Extract tomcat archive
    unarchive:
      src: "/usr/share/apache-tomcat-10.0.7.tar.gz"
      dest: /usr/share/
      owner: tomcat
      group: tomcat
      remote_src: yes

  
  - name: Symlink install directory
    shell: ln -sf /usr/share/apache-tomcat-10.0.7/ /usr/share/tomcat

  - name: Change ownership of Tomcat installation
    file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

  - name: Change ownership1 
    shell: "sudo chown -R tomcat:tomcat /usr/share/tomcat*"
 
  - name: Change ownership2
    shell: "sudo chown -R tomcat:tomcat /usr/share/apache-tomcat-10.0.7"
 
 
  - name: insert env into config
    shell: "tee /etc/systemd/system/tomcat.service<<EOF \n
    \n[Unit]\n
    Description=Tomcat Server\n
    After=syslog.target network.target\n

    [Service]\n
    Type=forking\n
    User=tomcat\n
    Group=tomcat\n
    \n\n
    Environment=JAVA_HOME=/usr/lib/jvm/jre\n
    Environment='JAVA_OPTS=-Djava.awt.headless=true'\n
    Environment=CATALINA_HOME=/usr/share/tomcat\n
    Environment=CATALINA_BASE=/usr/share/tomcat\n
    Environment=CATALINA_PID=/usr/share/tomcat/temp/tomcat.pid\n
    Environment='CATALINA_OPTS=-Xms512M -Xmx1024M'\n
    ExecStart=/usr/share/tomcat/bin/catalina.sh start\n
    ExecStop=/usr/share/tomcat/bin/catalina.sh stop\n
    \n
    \n
    [Install]\n
    WantedBy=multi-user.target\n"



  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true

  - name: Install Java 11
    lineinfile:
      path: /usr/share/tomcat/conf/tomcat-users.xml
      regexp: '</tomcat-users>'
      insertbefore: '</tomcat-users>'
      line: <role rolename="admin-gui"/>
             <role rolename="manager-gui"/>
             <user username="admin" password="1234" fullName="Administrator" roles="admin-gui,manager-gui"/>
             </tomcat-users>

  - name: install httpd
    yum: name=httpd state=present


  - name: insert env into config
    shell: "tee /etc/httpd/conf.d/tomcat_manager.conf<<EOF \n
    <VirtualHost *:80>\n
    ServerAdmin root@localhost\n
    ServerName tomcat.hirebestengineers.com\n
    DefaultType text/html\n
    ProxyRequests off\n
    ProxyPreserveHost On\n
    ProxyPass / http://localhost:8080/\n
    ProxyPassReverse / http://localhost:8080/\n
    </VirtualHost>"

  
  - name: "enable httpd startup"
    systemd:
      name: 'httpd'
      enabled: yes
      state: restarted
