---
## playbook to install a package

- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: "install xdiskusage"
      tags:
        - packages
      apt:
        state: present
        pkg:
          - xdiskusage
